#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "mdv"

begin
  MDV.new.main(ARGV)
rescue StandardError => error
  warn "mdv: #{error.message}"
  exit 1
end
